version: '2'

services:
  web:
      build: ./depthCameraRemoteControl
      user: nobody
      command: bash -c "python3 manage.py runserver 0.0.0.0:8000"
      volumes:
        - ./depthCameraRemoteControl:/code
      expose:
        - "8000"

  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/config:/etc/nginx/conf.d
    depends_on:
      - web

